project:
  render:
  - lessons/00-IntroductionAndSyllabus.qmd
  - lessons/01-RStudioProjectsAndGit.qmd
  - lessons/02-Components.qmd
  - lessons/_Info.qmd
  type: website
  output-dir: docs
#  title: "Graphing With GGPlot"  -- ugly in sidebar!
website:  
  bread-crumbs: false
  sidebar:
    # background: purple
    # foreground: yellow
    style: "floating"
    search: false
    contents:
      - section: "Graphing With GGPlot"
        contents:
          - text: "Info"
            file: lessons/_Info.qmd
          - text: "Intro and Syllabus"
            file: lessons/00-IntroductionAndSyllabus.qmd
          - text: "Projects"
            file: lessons/01-RStudioProjectsAndGit.qmd
          - text: "Components"
            file: lessons/02-Components.qmd
format:
  html:
    css: "presStyle.css"
    toc: true
    fig-align: left
    theme: default
    fontsize: 15px
    number-sections: true
    grid: 
      body-width: 1000px
    include-in-header:
      - text: |
          <script src="module.js"></script>
editor: visual
# title-slide-attributes:
#     data-background-image: "https://qfcatmsu.github.io/Images/dark-big.png"  
#     data-background-size: "40%"
#     data-background-position: "6% 95%"
# author: "Charlie Belinsky<br>belinsky@msu.edu"
# date-format: "D MMMM YYYY"
# date: today
# format: 
#   html:
#     css: ../presStyle.css
  #  slide-number: c/t
   # multiplex: true
   # controls: true
    #controls-layout: bottom-right
#    touch: true
 #   theme: simple
  # pdf:
 #   latex-auto-install: false  # use quarto update tinytex instead
    # toc: true
    # number-sections: true
    # colorlinks: true
  #  linestretch: 1.5
# highlight-style: kate
# include-after-body:
#   text: |
#     <script type="application/javascript" src="../presStyle.js"></script>
#     <!-- need a general place for this (github) -->