website:  
  bread-crumbs: false
  sidebar:
    search: true
    collapse-level: 1   # does not work because a page within is opened
    contents: 
      - section: "Graphing With GGPlot Lessons"  
        contents: lessons/*.qmd

project:
  render:
  - lessons/*.qmd
  type: website
  output-dir: docs

format:
  html:
    page-layout: full
    css: "https://qfcatmsu.github.io/assets/quarto/qfc_styles.css"
    toc: true
    toc-title: Lesson Content
    toc-location: left
    fig-align: left
    theme: default
    fontsize: 15px
    number-sections: true
    grid: 
      body-width: 1000px
    include-in-header:
      - text: |
          <script>mod=true;</script>
          <script src="https://qfcatmsu.github.io/assets/quarto/qfc_styles.js"></script>
editor: visual







# title-slide-attributes:
#     data-background-image: "https://qfcatmsu.github.io/Images/dark-big.png"  
#     data-background-size: "40%"
#     data-background-position: "6% 95%"
# author: "Charlie Belinsky<br>belinsky@msu.edu"
# date-format: "D MMMM YYYY"
# date: today
# format: 
#   html:
#     css: ../presStyle.css
  #  slide-number: c/t
   # multiplex: true
   # controls: true
    #controls-layout: bottom-right
#    touch: true
 #   theme: simple
  # pdf:
 #   latex-auto-install: false  # use quarto update tinytex instead
    # toc: true
    # number-sections: true
    # colorlinks: true
  #  linestretch: 1.5
# highlight-style: kate
# include-after-body:
#   text: |
#     <script type="application/javascript" src="../presStyle.js"></script>
#     <!-- need a general place for this (github) -->