website:  
  bread-crumbs: false
  sidebar:
    search: true
    collapse-level: 1   # does not work because a page within is opened
    contents: 
      - section: "Graphing With GGPlot Lessons"  
        contents: lessons/*.qmd

language:
  search-box-placeholder: Search All Lessons
# puts placeholder in but not the correct text

project:
  render:
  - lessons/*.qmd
  type: website
  output-dir: docs

format:
  html:
    page-layout: full
    css: "https://qfcatmsu.github.io/assets/quarto/qfc_styles.css"
    toc: true
    toc-title: Lesson Content
    toc-location: left
    fig-align: left
    theme: default
    fontsize: 15px
    number-sections: true
    grid: 
      body-width: 1000px
    include-in-header:
      - text: |
          <link rel = "shortcut icon" href = "https://qfcatmsu.github.io/assets/quarto/qfc_icon.png" />
          <script>mod=true; menuCollapse=true;</script>
          <script src="https://qfcatmsu.github.io/assets/quarto/qfc_styles.js"></script>
           
editor: visual