website:  
  bread-crumbs: false
  sidebar:
    search: true
    collapse-level: 1   # does not work...
    contents: 
      - section: "Graphing With GGPlot"  
        contents:
          - text: "- Info"
            file: lessons/Info.qmd
          - text: "0 Intro and Syllabus"
            file: lessons/00-IntroductionAndSyllabus.qmd
          - text: "1 Projects"
            file: lessons/01-RStudioProjectsAndGit.qmd
          - text: "2 Components"
            file: lessons/02-Components.qmd
          - text: "3 Mapping And Aesthetics"
            file: lessons/03-MappingAndAesthetics.qmd
          - text: "4 Elements And Styles"
            file: lessons/04-ElementsAndStyles.qmd
          - text: "5 Date Objects And Themes"
            file: lessons/05-DateObjectsAndThemes.qmd
          - text: "6 Modifying Mapped Elements"
            file: lessons/06-ModifyingMappedElements.qmd
          - text: "7 Faceting"
            file: lessons/07-Faceting.qmd
project:
  render:
  - lessons/00-IntroductionAndSyllabus.qmd
  - lessons/01-RStudioProjectsAndGit.qmd
  - lessons/02-Components.qmd
  - lessons/03-MappingAndAesthetics.qmd
  - lessons/04-ElementsAndStyles.qmd
  - lessons/05-DateObjectsAndThemes.qmd
  - lessons/06-ModifyingMappedElements.qmd  
  - lessons/07-Faceting.qmd
  - lessons/Info.qmd
  - lessons/test.qmd
  type: website
  output-dir: docs

format:
  html:
    page-layout: full
    css: "https://qfcatmsu.github.io/assets/quarto/qfc_styles.css"
    toc: true
    toc-title: Contents
    toc-location: left
    fig-align: left
    theme: default
    fontsize: 15px
    number-sections: true
    grid: 
      body-width: 1000px
    include-in-header:
      - text: |
          <script>mod=true;</script>
          <script src="https://qfcatmsu.github.io/assets/quarto/qfc_styles.js"></script>
editor: visual







# title-slide-attributes:
#     data-background-image: "https://qfcatmsu.github.io/Images/dark-big.png"  
#     data-background-size: "40%"
#     data-background-position: "6% 95%"
# author: "Charlie Belinsky<br>belinsky@msu.edu"
# date-format: "D MMMM YYYY"
# date: today
# format: 
#   html:
#     css: ../presStyle.css
  #  slide-number: c/t
   # multiplex: true
   # controls: true
    #controls-layout: bottom-right
#    touch: true
 #   theme: simple
  # pdf:
 #   latex-auto-install: false  # use quarto update tinytex instead
    # toc: true
    # number-sections: true
    # colorlinks: true
  #  linestretch: 1.5
# highlight-style: kate
# include-after-body:
#   text: |
#     <script type="application/javascript" src="../presStyle.js"></script>
#     <!-- need a general place for this (github) -->